class AuthenticationError(Exception):
    pass


class RetryException(Exception):
    pass
